### PR TITLE
Add test cases for MarkSyll, EraseSyll

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by ongyz — APPROVED** [review]
Test cases are effective! Everything looks good

**Review by andlimey — APPROVED** [review]
Thanks for adding the test cases!

**Review by lywjoel — CHANGES_REQUESTED** [review]
Needs newline characters at end of EraseSyllCommandTest.java and MarkCommandTest.java!

**Comment by ghost** [comment]
Fixed style violation

**Pull request merged**
